### ISSUE TITLE
qt5.12

### ISSUE THREAD

**Issue by looooo** [conda-forge/qt-feedstock#101]
I wonder what people think about updating this feedstock to qt5.12. 
We see different problems with qt5.6.2 on osx and linux (freecad-feedstock) and think updating qt would solve some of them. So we are definitely interested into qt5.12.

I know qt is one of the most difficult packages in conda-forge, but it's more likely to get done if more people are interested in this task. So maybe other maintainers interested in qt5.12 can show up here and give their opinon about how and when this conda-forge qt5.12 should happen. I guess  one of the main interests of anaconda to provide qt is spyder. So maybe asking @ccordoba12 what he thinks about updating this feedstock.

@mingwandroid has already build a package of qt5.12 for osx. So maybe he can give some insights on what has to be done for the other platforms.

**Comment by ccordoba12** [comment]
> So maybe asking @ccordoba12 what he thinks about updating this feedstock.

We in Spyder are already well covered by the excellent packages created by @mingwandroid for Anaconda. conda-forge is a community effort, so it depends on the time and good will of volunteers to run.

Until @mingwandroid updates Qt to 5.12 in Anaconda, I think there's no point in trying to do that here. The builds don't pass on Azure even after 6 hours, as PR #88 showed (except for macOS), so there's no way to see if things are working. Besides, it's an extremely time consuming effort for volunteers.

The good thing about PR #88 is that it showed that the recipes for Qt 5.9 are working very well, so we need to resort to what we've done several times in the past: compile locally for Linux and Windows and upload the packages to Anaconda.

I could help with Linux. @gillins, do you have time to help us with Windows?

**Comment by gillins** [comment]
> @gillins, do you have time to help us with Windows?

:+1: I don't have a lot of expertise with Qt on Windows, but will help where I can. I have Windows hardware to do builds on.

**Comment by ccordoba12** [comment]
Great!! Thanks a lot @gillins! Let's work on PR #88 to see if we can manage to get this done.

**Comment by isuruf** [comment]
Can anybody give me ssh access to a windows server to debug qt 5.12 on windows?

**Comment by msarahan** [comment]
I can try to set you up with an RDP connection.  The computer is not great, though - old Phenom II x6.  You'd also need to set up compilers and stuff.  Unfortunately my nicer win machine only has win 10 home.

**Comment by isuruf** [comment]
> The computer is not great, though - old Phenom II x6. 

Sounds better than my current solution (VM on top of ubuntu)

> Unfortunately my nicer win machine only has win 10 home.

It's been a while since I used windows. What's the difference?

**Comment by msarahan** [comment]
win 10 pro allows RDP, win 10 home does not. =(

**Comment by msarahan** [comment]
I think I can find another way.  Nomachine or vnc or something.
