### ISSUE TITLE
Build qt5.9 webkit

### ISSUE THREAD

**Issue by looooo** [conda-forge/qt-feedstock#107]
What is the plan for the webkit. I have some issues with webengine, so it would be nice to have an option to install webkit for qt5.9.

**Comment by ccordoba12** [comment]
There are no plans, sorry.

**Comment by gillins** [comment]
There is an archived feedstock here: https://github.com/conda-forge/qtwebkit-feedstock if you want to get it going again

**Comment by looooo** [comment]
thanks @gillins . I will have a look.

**Comment by ocefpaf** [comment]
If you want make that work and want to send a PR let me know so I can restore it from the archive. We cannot maintain it but it is available to new maintainers.

**Comment by looooo** [comment]
FreeCAD now runs with qtwebengine. So qtwebkit is not needed anymore.
