### ISSUE TITLE
qt5.12 windows libpng not pinned to version 1.6.35 

### ISSUE THREAD

**Issue by looooo** [conda-forge/qt-feedstock#113]
libpng should be pinned to 1.6.35 (only qt5.12 for windows requires libpng 1.6.37):

https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/bcde19e5ed214c264513d2237112f987e3c03af0/recipe/conda_build_config.yaml#L469

This results in conflicting packages eg. here:
https://github.com/conda-forge/simage-feedstock/pull/10#issuecomment-519808391

**Comment by isuruf** [comment]
Will be fixed with https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/262

**Comment by isuruf** [comment]
Rerender that PR and it should work.
