### ISSUE TITLE
Version compatbility

### ISSUE THREAD

**Issue by gabm** [conda-forge/qt-feedstock#119]
Issue: The current qt version (5.12.1) pins to X.X which results in a package pin compatibility of ">= 5.12.1 and <= 5.13.0a". Now, I have a package that was built against 5.9.7 and I can't install that package alongside a newer package that was built against version 5.12.1 because of:

```
pkgA -> qt[version='>=5.12.1,<5.13.0a0']
pkgB -> qt[version='>=5.9.7|>=5.9.7,<5.10.0a0']
```

As far as I know the, Qt tries to be backward compatible and in fact, it mostly is: https://abi-laboratory.pro/index.php?view=timeline&l=qt

Could we pin in a way that reflects that? for example >= 5.12.1 to allow compatibility with future versions without rebuild?

**Comment by mingwandroid** [comment]
> and in fact, it mostly is

Sorry, *mostly* is not good enough, all it takes is one deleted symbol and BC is dead.

Qt may in general promise backwards compatibility (even if they don't achieve it) but I doubt our packages promise or provide that, but I am happy to be wrong.

If we were to pin to Qt 5.6 as a minimum that would require us to always build against 5.6 (so no new APIs get linked to) which would prevent usage of (for example) pyside2 and prevent us from being able to build things like newer RStudios or QtCreators.

Overall I don't think this is wise, sorry.

**Comment by mingwandroid** [comment]
Feel free to reopen this if you can disprove my statements!
