### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/qt-feedstock#14]
This issue is to keep track of what we can build. When an item passes I will add a skip statement to that one and commit direct to master to re-try the remaining items.

- [X] TARGET_ARCH=x86, CONDA_PY=27
- [X] TARGET_ARCH=x64, CONDA_PY=27 (manual upload)
- [X] TARGET_ARCH=x86, CONDA_PY=34
- [X] TARGET_ARCH=x64, CONDA_PY=34
- [X] TARGET_ARCH=x86, CONDA_PY=35 (manual upload)
- [X] TARGET_ARCH=x64, CONDA_PY=35 (manual upload)

**Comment by ocefpaf** [comment]
3 out of 6 not bad

**Comment by ocefpaf** [comment]
@gillins do you think you can build

```
 TARGET_ARCH=x64, CONDA_PY=27
 TARGET_ARCH=x86, CONDA_PY=35
 TARGET_ARCH=x64, CONDA_PY=35
```

locally? I was unable to get those to complete within the 1-hour limit :cry:

**Comment by ccordoba12** [comment]
Are they up in the conda-forge channel already?

**Comment by ocefpaf** [comment]
Yep.

https://anaconda.org/conda-forge/qt/files

**Comment by ccordoba12** [comment]
Nice! I'll give you a hand with macOS this week (the recipe needs some tweaks to used libc++ instead of libstdc++).

**Comment by ocefpaf** [comment]
Thanks @ccordoba12!

**Comment by gillins** [comment]
> @gillins do you think you can build

Should be able to - will look at this today

**Comment by ocefpaf** [comment]
Thanks a lot @gillins!

**Comment by gillins** [comment]
Minor point, but currently `msvc_2015_includes.patch` doesn't seem to be applied. Seems fine without it, not sure if it should be removed or not....

**Comment by gillins** [comment]
Builds done. @ocefpaf I've sent you an email with the link.

**Comment by ocefpaf** [comment]
> Minor point, but currently `msvc_2015_includes.patch` doesn't seem to be applied. Seems fine without it, not sure if it should be removed or not....

I will look into it. (Any ideas @ccordoba12?)

> Builds done. @ocefpaf I've sent you an email with the link.

Got it. Thanks! I will upload them soon.

**Comment by ocefpaf** [comment]
The packages are in the channel. Closing this.

Thanks @gillins for the builds and @ccordoba12 for the review!
