### ISSUE TITLE
wrong osx min version

### ISSUE THREAD

**Issue by beckermr** [conda-forge/qt-feedstock#169]
It appears in my local build for master, the wrong min osx version is being specified to the compiler

```
$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-clang++ -c -o qmap.o -fconstant-cfstrings -MMD -stdlib=libc++ -isysroot /Users/beckermr/Desktop/qt-feedstock/MacOSX10.12.sdk -mmacosx-version-min=10.12 -std=c++11 -ffunction-sections -fdata-sections -g -g  -I$SRC_DIR/qtbase/qmake -I$SRC_DIR/qtbase/qmake/library -I$SRC_DIR/qtbase/qmake/generators -I$SRC_DIR/qtbase/qmake/generators/unix -I$SRC_DIR/qtbase/qmake/generators/win32 -I$SRC_DIR/qtbase/qmake/generators/mac -I$SRC_DIR/qtbase/include -I$SRC_DIR/qtbase/include/QtCore -I$SRC_DIR/qtbase/include/QtCore/5.12.9 -I$SRC_DIR/qtbase/include/QtCore/5.12.9/QtCore -I../src/corelib/global -I$SRC_DIR/qtbase/mkspecs/macx-clang -DQT_VERSION_STR=\"5.12.9\" -DQT_VERSION_MAJOR=5 -DQT_VERSION_MINOR=12 -DQT_VERSION_PATCH=9 -DQT_BUILD_QMAKE -DQT_BOOTSTRAPPED -DPROEVALUATOR_FULL -DQT_NO_FOREACH $SRC_DIR/qtbase/src/corelib/tools/qmap.cpp
```

It is this flag `-mmacosx-version-min=10.12` in particular that is worrying.

**Comment by beckermr** [comment]
cc @isuruf

**Comment by mingwandroid** [comment]
The flag is ignored when CONDA_BUILD_SYSROOT is set as far as I remember.. could be wrong though.

**Comment by beckermr** [comment]
Thanks @mingwandroid.

I think qt has a min SDK version of 10.12 in the recipe anyways for osx. IDK why the CBC has the other min in it but this appears to be fine. Closing!

**Comment by isuruf** [comment]
2 lines at https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml#L93-L95 should be removed. They are redundant. PRs welcome
