### ISSUE TITLE
No recent version with qt available on all platforms with icu=67

### ISSUE THREAD

**Issue by xhochy** [conda-forge/qt-feedstock#173]
Seems like we don't have a qt version which is available for OSX + Win + Linux at the same time and also supports icu=67. Thus I'm unable to finish up the `icu=67` migration. 

* `5.15.5`: No build for Windows and `icu=67`
* `5.15.6`: No OSX build
* `5.15.9`: No Windows build

I need a version that is available for all OSes as https://github.com/conda-forge/qgis-feedstock/pull/147 is pinned through `qtlocation` to the minor version of `qt`. Updating `qtlocation` requires a qt minor version with builds on all of the OSes.

Options here:

* Someone rebuilds for Windows (@ocefpaf ?)
* We do a rerender and build for `5.15.6` on a branch and get a build for OSX for that minor version.

**Comment by ocefpaf** [comment]
> Someone rebuilds for Windows (@ocefpaf ?)

Sure. I'll try to build it tonight with my Windows laptop.
Unless @isuruf beats me to it and test for the OVH machine.

**Comment by isuruf** [comment]
Fails with `%SRC_DIR%\qtbase\src\3rdparty\angle\src\libANGLE\renderer\d3d\d3d11\texture_format_table_autogen.cpp : fatal error C1083: Cannot open compiler generated file: '': Invalid argument`

**Comment by isuruf** [comment]
Done

**Comment by isuruf** [comment]
Note to future self. Above error happens when the build directory path length is too long.

**Comment by xhochy** [comment]
Thanks!

**Comment by ocefpaf** [comment]
> Note to future self. Above error happens when the build directory path length is too long.

BTW, you told me to change it to a shorter path a long time ago ;-p

**Comment by mingwandroid** [comment]
I am tempted to add some build/max_build_dir_len so we can exit build attempts that try to exceed that?
