### ISSUE TITLE
Update to 5.12.10

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/qt-feedstock#188]
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by Tobias-Fischer** [comment]
See https://github.com/conda-forge/qt-feedstock/pull/206
