### ISSUE TITLE
Split qt-webengine

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/qt-feedstock#192]
Seems like qt-webengine is taking up 93MB/173MB of the qt package.

I'm not sure a whole lot of packages utilize it, and therefore I think it would be beneficial to split it off.

Seems like Fedora builds off sources available in :
https://download.qt.io/official_releases/qt/5.12/5.12.10/submodules/

https://src.fedoraproject.org/rpms/qt5-qtwebengine/blob/rawhide/f/qt5-qtwebengine.spec

We can likely follow their build process and this one to split build qt into two steps:

1. No web-engine
2. Web-engine only

CC: @wolfv

**Comment by mingwandroid** [comment]
Definitely agree to a split.  Either entirely like archlinux does oe just Webengine as a first step.

**Comment by hmaarrfk** [comment]
If this can be downloaded using a seperate source, I would recommend using a different feedstock.

I think it would help alleviate the build time on this particular repository allowing us to build on the CIs instead.

**Comment by mingwandroid** [comment]
Qt provides separate archives per module. Yes.

**Comment by wolfv** [comment]
I think we can handle Qt 6 completely separate from Qt 5 and do clean splits for Qt 6 and continue with Qt 5 here (maybe with qt-webengine split out as a separate output?).

**Comment by isuruf** [comment]
I'm not a fan of half-measures like doing a change in Qt 5 and then doing more changes in Qt 6.

**Comment by mingwandroid** [comment]
Afaik qt 6 is still not really ready for the prime time (like to be wrong). But maybe we should get that working as well as we can and see. If it's still not ready we could contemplate fully splitting qt5. In this case though given that webengine is such a huge chunk of the code, build time and problems we face i don't mind splitting qt5s webengine at least as a first step.

The thing we really need is some progress..

**Comment by wolfv** [comment]
Without webengine we could also have a Apple Silicon build much quicker

**Comment by isuruf** [comment]
> Without webengine we could also have a Apple Silicon build much quicker

If this is your goal, we can disable webengine for just Apple silicon.

**Comment by mingwandroid** [comment]
Splitting has great value for recipe development here i think. I hate not working on this as it stands. Let's split all of qt5 if we must!

**Comment by isuruf** [comment]
I agree that splitting everything is useful, but we should do it correctly and it might take a while to get it correctly. I just don't want to do it in a hurry.

**Comment by hmaarrfk** [comment]
> If this is your goal, we can disable webengine for just Apple silicon and not do any splitting.

I don't understand why this would be acceptable or desirable.

We should plan out how to split the whole thing, but with limited resources, i am not sure the best use v of v then is to split every qt feature.

Qt qtwebengine is almost half the build time. It would cut the space in half, and allow us to use CIs for qt again.

**Comment by hmaarrfk** [comment]
we can outline a few packages to start itting off, but i feel like webengine would be at the top of the liat.

**Comment by mingwandroid** [comment]
We must split them off in dependency order here mark.. webengine must be built in the presence of already split qt-base and qt-tools four example. I think we probably need to just do it fully really. 

You can use tools from other distos to get a tree of deps, eg pactree from arch Linux.

**Comment by ccordoba12** [comment]
Hey everyone here and @conda-forge/qt, @andfoy (from the Spyder team) is working on updating Qt/PyQt to 5.15 in Conda-forge, thanks to a contract with Quansight.

We also think it's really good idea to split Qtwebengine to its own package because then it'd be possible to compile the rest of Qt in CIs and be updated it more frequently by the community.

In order to make that transition easier for users and maintainers, we propose to create another package called `qt-base` which would contain the rest of Qt. Then, the Qt package would become a meta-package that would simply install `qt-base` and `qtwebengine`.

Please take into account that we don't have enough hours in our contract to split every single Qt library into its own package. In addition, that would complicate things for PyQt: should it be split in its own submodules as well to be consistent? That's perhaps not something that regular users would expect because the pip PyQt is not split like that, so it could open an expected, ugly and perhaps unnecessary can of worms.

What do you think?

**Comment by ccordoba12** [comment]
I forgot to mention that you can follow @andfoy's progress on this repo, in case you're interested:

https://github.com/andfoy/qt-recipe

**Comment by isuruf** [comment]
`qt-base` is not a good name as `base` is a qt module, just like `webengine` is also a qt module.

**Comment by isuruf** [comment]
> In addition, that would complicate things for PyQt: should it be split in its own submodules as well to be consistent?

Nope. PyQt should match upstream and not be split.

**Comment by ccordoba12** [comment]
> qt-base is not a good name as base is a qt module, just like webengine is also a qt module.

@isuruf, we're just trying to follow the same convention of other packages, like `matplotlib-base` (present here) and `numpy-base` (not present here but in defaults). Those packages don't exist as real Python modules and yet they do as conda packages for convenient reasons.

The other option would be to follow the same split done by pip PyQt with Qt too, i.e. leaving this feedstock to contain everything but Webengine, and move Webengine and PyQtWebengine to their own feedstocks. That would break the current way of installing Qt, but it'd have the advantage of making things easier to understand for users and, especially, other package developers in the future. Most Qt/PyQt applications either require Webengine or not (Matplotlib and Qtconsole don't, but Spyder does). However, they usually expect the rest of Qt to work (I'm talking by experience, maintaining a significant array of PyQt related packages for several years).

**Comment by ccordoba12** [comment]
> qt-base is not a good name as base is a qt module, just like webengine is also a qt module.

Also, this statement is incorrect. What exists is [QtCore](https://doc.qt.io/qt-5/qtcore-index.html), not QtBase as a module.

**Comment by isuruf** [comment]
> @isuruf, we're just trying to follow the same convention of other packages, like matplotlib-base (present here) and numpy-base (not present here but in defaults). Those packages don't exist as real Python modules and yet they do as conda packages for convenient reasons.

That's exactly my point. There's no real python module called `matplotlib-base`, so that's fine. There's a real module called `qtbase`. See https://github.com/qt/qtbase/

**Comment by ccordoba12** [comment]
Ok, I understand your point now. But that's not a Qt module, it's a collection of Qt modules, as you can read in the About of the repo

> Qt Base (Core, Gui, Widgets, Network, ...) 

and looking at its `src` directory:

https://github.com/qt/qtbase/tree/dev/src

Also, if you browse the Qt docs, you won't find a reference to qt-base as a module.

**Comment by hmaarrfk** [comment]
I'm ok with the partial split. I think it is a good use of your time. I think the problem with naming things `qt-base` (with or without a dash)

Is that on the way to a full split, we would create a package that is more than what qtbase means upstream.

Since they do provide a tar file for it. You can find it here https://download.qt.io/official_releases/qt/5.12/5.12.10/submodules/

I'm not sure of a better name. Sorry I can't be more constructive.

`qt-core`???

**Comment by ccordoba12** [comment]
Thanks for chiming in @hmaarrfk!

> Is that on the way to a full split, we would create a package that is more than what qtbase means upstream.

Right, that's a good point.

> qt-core???

That's taken too: https://doc.qt.io/qt-5/qtcore-index.html

What about `qt-main` or `qt-basic`?

**Comment by hmaarrfk** [comment]
i can say I'm that much of a fan of either.

is there an other way to think about it?
what do you need for PyQt and Pyside? Do you just need base?

if so, maybe let's create a muted to allow you to build packages for tools and base, and then othera can pick up the other packages????

**Comment by ccordoba12** [comment]
> what do you need for PyQt and Pyside? Do you just need base?

The pip PyQt comes with base and other libraries, such as

* QtBluetooth
* QtMultimedia
* QtQml
* QtQuick

Our idea is to follow the same pattern for both Qt and PyQt in Conda-forge.

> if so, maybe let's create a muted to allow you to build packages for tools and base, and then othera can pick up the other packages????

What do you mean by this?

**Comment by hmaarrfk** [comment]
>>    if so, maybe let's create a muted to allow you to build packages for tools and base, and then othera can pick up the other packages????
>
>What do you mean by this?

I'm wondering if there is a way for us to slowly transition to a fully split Qt package that doesn't put all the work on you.

For example, if we can setup a mutex, for a single/split qt build system, then users can stay on the `single` version of qt, until we've built enough to get PyQt (and PySide) off the ground.

This would mean that you don't have to do split the whole thing up in one go.

**Comment by ccordoba12** [comment]
Ok, I see. You could work on that after we update Qt because @andfoy is almost done with his work.

**Comment by Tobias-Fischer** [comment]
This is finally done :). Should we close @hmaarrfk ?
