### ISSUE TITLE
Issue with jpeg dependency on Windows

### ISSUE THREAD

**Issue by hadim** [conda-forge/qt-feedstock#2]
The qt version that conda provides (even with conda-forge enabled) depends on jpeg-8d. This dependency prevents me to install the new opencv 3.1.0 (see https://github.com/conda-forge/opencv-feedstock/issues/27).

The repo seems to update the jpeg dep to 9. See https://github.com/conda-forge/qt-feedstock/blob/master/recipe/meta.yaml#L55

How can I access to the build of this repo ? I can't find them with `conda search qt --channel conda-forge`

**Comment by jakirkham** [comment]
This is only built on Linux. There are no Windows or OS X builds. On the OS X side, the blocker is CI limitations. Not sure what the Window blocker is (possibly also CI limitations).

**Comment by hadim** [comment]
Ok.

**Comment by ccordoba12** [comment]
We could try to build this for Windows, but I don't have time to do it right now :-)

**Comment by patricksnape** [comment]
@ccordoba12 Do we have a working recipe for QT somewhere? In my experience the Appveyor guys are pretty responsive/happy to increase builder capabilities for open source package builds.

**Comment by ccordoba12** [comment]
It's here in the repo :-)

**Comment by patricksnape** [comment]
😊 Whoops! OK just need a PR that kicks off a build that we can refer to (which will presumably fail due to timeouts).

**Comment by ocefpaf** [comment]
@patricksnape and @ccordoba12 if we can get a working recipe we should discuss the possibility to build it outside `AppVeyor`. Maybe we should put together a vagrant config for this first.

I am a zero on Windows and vagrant so I won't be able to help much there...

**Comment by patricksnape** [comment]
@ocefpaf Build it where? How would we even know it works?

**Comment by ocefpaf** [comment]
> @ocefpaf Build it where? 

There are many people willing to donate hardware for this. We need only to find a way to ensure the vagrant config is compatible. 

> How would we even know it works?

By testing!

**Comment by patricksnape** [comment]
I understand that someone would run it but the question is how they demonstrate that it actually works. That sounds like an extremely ambitious sub-project to me - since by the time we'd got it working I imagine we'd nearly have our own version of Appveyor... Especially if we want that hardware to get kicked off by PRs!

**Comment by ocefpaf** [comment]
> That sounds like an extremely ambitious sub-project to m

It is.

>  since by the time we'd got it working I imagine we'd nearly have our own version of Appveyor...

Indeed.

>  Especially if we want that hardware to get kicked off by PRs!

That would be the dream :smile: 

The thing is. we are already at the limit with AppVeyor. If anyone wants to try asking for more please go ahead. But we already contact them more than once and got all the resources they could offer already.

**Comment by patricksnape** [comment]
Ah well then this seems more like we should just be setting up some general system for Windows/vagrant builds (essentially building our own CI) and achieving that before using QT as our guinea pig?

**Comment by ocefpaf** [comment]
> Ah well then this seems more like we should just be setting up some general system for Windows/vagrant builds (essentially building our own CI) and achieving that before using QT as our guinea pig?

Why? Qt's issues on Windows makes it the perfect `guinea pig` for testing this and, if successful, be used in other long builds. Either way please add you opinions to the meeting agenda: https://conda-forge.hackpad.com/conda-forge-meetings-2YkV96cvxPG

We already have a few topics on long builds and I am very interested you hearing more from you.

PS: If you want to attend the next meeting, and I encourage you to, please also answer the doodle regarding the time of the meeting.

**Comment by patricksnape** [comment]
I can do the 9th - I filled in the doodle.

**Comment by ocefpaf** [comment]
> I can do the 9th - I filled in the doodle.

Awesome! Thanks!!

Note that google hangout has a 10 people limit but do not go away if we reach that limit the time you try to connect. I will gladly switch places with you in the meeting so you can participate. We need more Windows voices there!

**Comment by msarahan** [comment]
This is already in the works on the Continuum side.  Some mix of Gitlab CI driving vagrant/docker/virtualbox.  I created this issue as a rallying point: https://github.com/conda/build_infrastructure/issues/1

The point will be less to create a general appveyor/travis/circle replacement, and more to provide a way to build our specific desires, and have a way for everyone to contribute build server time, since that is much more straightforward than financial arrangements.

**Comment by msarahan** [comment]
Also, if we anticipate more than 10 people, we can try WebEx, or perhaps bluejeans.

**Comment by ocefpaf** [comment]
This should be fixed now. Thanks to all for the support and help solving this.

Next step... Qt 5 :smile:
