### ISSUE TITLE
Next LTS release?

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/qt-feedstock#200]
Qt 5.12 is EOL on 2021-12-05.

Next LTS is 5.15, but allegedly [only for commercial](https://lists.qt-project.org/pipermail/development/2021-January/040798.html) license holders:

> With Qt 6.0.0 released and the first patch release (Qt 6.0.1) coming soon, it is time to enter the commercial-only LTS phase for Qt 5.15 LTS. All the existing 5.15 branches remain publicly visible, but they are closed for new commits (and cherry-picks). Exception being the Qt WebEngine (and the deprecated Qt Script), which have a 3rd party LGPL dependency.
>
> Closing happens tomorrow, 5th January 2021. After this the cherry-picks go to another repository that will be available only for the commercial license holders. We will arrange repository access to the commercial license holders, so in addition to the official releases it is possible to use the repositories. Instructions about this will be available to commercial license holders during next week, after we have completed the license change and other preparations.
>
> First commercial-only Qt 5.15.3 LTS patch release is planned to be released in February.
>
> We can arrange access for external module maintainers to the commercial-only repositories. If there is interest, please contact me or Tarja Sundqvist tarja.sundqvist at qt.io<mailto:tarja.sundqvist at qt.io> who is the release manager for the commercial-only LTS releases.

In practice, I guess that means 5.15 is not LTS for us. So... Qt 6.x it is? The [next LTS will be 6.2](https://www.qt.io/blog/qt-roadmap-for-2021), but it will have the same treatment as 5.15: once 6.3 is released, LTS will only be available for commercial users. 

There's also the [KDE-maintained series of patches](https://www.phoronix.com/scan.php?page=news_item&px=KDE-Qt-5-Patch-Collection) on top of 5.15.2, which could provide some room there. They don't do releases though.

Thoughts @conda-forge/core?

**Comment by Tobias-Fischer** [comment]
See https://github.com/conda-forge/qt-feedstock/pull/206
