### ISSUE TITLE
Bump icu to 58.*

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/qt-feedstock#29]
Seems everything else is using 58.* at this point. Would it be reasonable to also bump qt to 58.*?

Note: I have not been following the icu update at all. So if this is already answered somewhere, please just let me know.

**Comment by parente** [comment]
I'm not up to speed at all about the icu pinning. I did just find that [matplotlib has icu pinned to icu 58.*](https://github.com/conda-forge/matplotlib-feedstock/blob/master/recipe/meta.yaml#L47) and winds up installing qt=4.8.7 because latest here (5.6.2) has icu pinned to 56.*.

**Comment by ocefpaf** [comment]
matplotlib cannot use qt5 from conda-forge yet. we are having some issues
compiling pyqt with qt5. I will get back to that soon. meanwhile we still
need to pin everything in conda-forge to qt4

**Comment by parente** [comment]
Thanks @ocefpaf. I found this because I wound up with broken geopandas and lxml installs (they both look for libicui18n.so.58) in an environment with qt also installed for matplotlib which pulls in icu 56.1 instead.

**Comment by ocefpaf** [comment]
I will take a look at this tomorrow. (I moved to another city right in the
middle of the icu change so things ended up incomplete).

**Comment by ocefpaf** [comment]
@parente you may be hitting a channel mismatch there. Qt4 is used everywhere in conda-forge and it is pinned to icu 58.*

See https://github.com/conda-forge/qt-feedstock/blob/qt4/recipe/meta.yaml

Hopefully qt5, with icu 58, will be available soon.

**Comment by parente** [comment]
Interesting. I'll take another pass through the package list.

**Comment by ocefpaf** [comment]
@parente let me know if you still suffer from this. Like I mentioned above you should not get `Qt5` from conda-forge since everything is still pinned to `Qt4`, and will remain like that for a while until we can build `Qt5` on Windows and `OS X`. 

I am closing this to avoid confusing users. `Qt4` **is** pinned and people should **not** rely on `Qt5` from conda-forge at the moment.

**Comment by parente** [comment]
I think the problem I'm seeing is due to graphviz. Still tracking it down, but here's 

```
# works fine
conda create -p /tmp/foo python=2.7 -c conda-forge 'matplotlib>=2.0' 'icu>=58'

# works fine
conda create -p /tmp/foo python=2.7 -c conda-forge python-graphviz 'icu>=58'

# winds up installing icu=56.*
conda create -p /tmp/foo python=2.7 -c conda-forge python-graphviz 'matplotlib>=2.0'

# package in conflict
conda create -p /tmp/foo python=2.7 -c conda-forge  'matplotlib>=2.0' 'icu>=58' python-graphviz
```

**Comment by ocefpaf** [comment]
Thanks. That helps. The culprit graphviz that is not properly pinned to latest libpng and is forcing a different build of matplotlib to be installed. 

I will fix that soon.

**Comment by parente** [comment]
All of these packages switch to defaults channel when I specify `icu>=58.0` and graphviz together. libpng seems to remain at the same version from conda-forge , 1.6.28-0.

```
    cairo:           1.12.18-6        defaults
    fontconfig:      2.11.1-6         defaults
    freetype:        2.5.5-2          defaults
    harfbuzz:        0.9.39-1         defaults
    pango:           1.39.0-0         defaults
````

**Comment by ocefpaf** [comment]
> I was thinking the pinning problem might be in one of these.

I am pretty sure it is `graphviz`. That feedstock is not updated in ages. Should be fixed soon.

**Comment by ocefpaf** [comment]
I guess that updating the pinning was all we needed.

```
> conda create -c conda-forge -n TEST python=2.7 python-graphviz
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /home/filipe/miniconda3/envs/TEST:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libtool-2.4.6              |                0         572 KB  conda-forge
    python-2.7.12              |                2        13.8 MB  conda-forge
    certifi-2017.1.23          |           py27_0         222 KB  conda-forge
    setuptools-33.1.0          |           py27_0         492 KB  conda-forge
    wheel-0.29.0               |           py27_0          81 KB  conda-forge
    pip-9.0.1                  |           py27_0         1.6 MB  conda-forge
    graphviz-2.38.0            |                4        12.6 MB  conda-forge
    python-graphviz-0.5.1      |           py27_0          17 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        29.3 MB

The following NEW packages will be INSTALLED:

    ca-certificates: 2017.1.23-0      conda-forge
    cairo:           1.14.6-4         conda-forge
    certifi:         2017.1.23-py27_0 conda-forge
    expat:           2.1.0-2          conda-forge
    fontconfig:      2.12.1-4         conda-forge
    freetype:        2.7-1            conda-forge
    gettext:         0.19.7-1         conda-forge
    glib:            2.51.4-0         conda-forge
    graphite2:       1.3.9-0          conda-forge
    graphviz:        2.38.0-4         conda-forge
    harfbuzz:        1.4.3-0          conda-forge
    icu:             58.1-1           conda-forge
    jpeg:            9b-0             conda-forge
    libffi:          3.2.1-3          conda-forge
    libiconv:        1.14-4           conda-forge
    libpng:          1.6.28-0         conda-forge
    libtiff:         4.0.6-7          conda-forge
    libtool:         2.4.6-0          conda-forge
    libxml2:         2.9.4-4          conda-forge
    ncurses:         5.9-10           conda-forge
    openssl:         1.0.2h-3         conda-forge
    pango:           1.40.4-0         conda-forge
    pcre:            8.39-0           conda-forge
    pip:             9.0.1-py27_0     conda-forge
    pixman:          0.34.0-0         conda-forge
    python:          2.7.12-2         conda-forge
    python-graphviz: 0.5.1-py27_0     conda-forge
    readline:        6.2-0            conda-forge
    setuptools:      33.1.0-py27_0    conda-forge
    sqlite:          3.13.0-1         conda-forge
    tk:              8.5.19-1         conda-forge
    wheel:           0.29.0-py27_0    conda-forge
    xz:              5.2.2-0          conda-forge
    zlib:            1.2.11-0         conda-forge
```
