### ISSUE TITLE
undefined symbol in phonon for osx

### ISSUE THREAD

**Issue by jschueller** [conda-forge/qt-feedstock#34]
Since qt(4) is in conda-forge, the build of pyside fails for osx since tests attempt to load phonon with missing symbols (https://s3.amazonaws.com/archive.travis-ci.org/jobs/214258733/log.txt):
```
from PySide import phonon

ImportError: dlopen(/Users/travis/miniconda3/conda-bld/pyside_1490279798328/work/PySide-1.2.4/sources/pyside/build/PySide/phonon.so, 2): Symbol not found: __ZN6Phonon22ObjectDescriptionModelILNS_21ObjectDescriptionTypeE0EE11qt_metacastEPKc

  Referenced from: /Users/travis/miniconda3/conda-bld/pyside_1490279798328/work/PySide-1.2.4/sources/pyside/build/PySide/phonon.so

  Expected in: flat namespace

 in /Users/travis/miniconda3/conda-bld/pyside_1490279798328/work/PySide-1.2.4/sources/pyside/build/PySide/phonon.so
```

```
$ c++filt _ZN6Phonon22ObjectDescriptionModelILNS_21ObjectDescriptionTypeE0EE11qt_metacastEPKc
Phonon::ObjectDescriptionModel<(Phonon::ObjectDescriptionType)0>::qt_metacast(char const*)
```

Sounds a bit like https://bugreports.qt.io/browse/QTBUG-37209

**Comment by jschueller** [comment]
you included it recently @jakirkham, why is it marked test ?

**Comment by jakirkham** [comment]
xref: https://github.com/conda-forge/qt-feedstock/issues/15#issuecomment-287202192

Though we should definitely test it with `pyqt` and `pyside`.

cc @gillins

**Comment by gillins** [comment]
@jschueller have you tried recompiling Qt with the patch you linked to? Does it resolve the problem? If so might be worth putting in a PR so we can get @jakirkham to rebuild.

Have you tried `pyqt`?

**Comment by jschueller** [comment]
the problem is when linking pyside.phonon, not qt. I did not try pyqt.

**Comment by jakirkham** [comment]
Would be good to try PyQt when you have a chance as well.

**Comment by jschueller** [comment]
I tried too: https://github.com/conda-forge/pyqt-feedstock/issues/19

**Comment by jakirkham** [comment]
Ah, but we've only built Qt4 thus far. That doesn't work with PyQt5, correct?

**Comment by jschueller** [comment]
this issue is osx/qt4 specific, conda-forge/pyqt-feedstock#19 is about (py)qt5 yes.

**Comment by jakirkham** [comment]
Thanks @jschueller. Was this using the `qt` 4 package I built for `conda-forge` or was this the one from `defaults`? I'm guessing it is the latter.

The main reason I ask is I'm trying to figure out if we can move the `qt` 4 package from `test` into `main`. If the one I built has the same issues, maybe we should patch it (if you have a patch that works) and retry. If the one I built doesn't have issues, that seems like a good argument for releasing it.

**Comment by jschueller** [comment]
it was qt 4.8.7-7 from conda-forge hence the bug report here:
```
qt-4.8.7                   |                7        35.9 MB  conda-forge
```
https://s3.amazonaws.com/archive.travis-ci.org/jobs/214258733/log.txt

**Comment by gillins** [comment]
@jschueller The link you sent about a similar problem (https://bugreports.qt.io/browse/QTBUG-37209) seems to suggest Qt4 needs to be rebuilt with a patch to `src/3rdparty/phonon/phonon/objectdescriptionmodel.h`. I was wondering if you rebuilt the qt-feedstock (`qt4` branch) with this patch and installed it, then tried `pyside` etc if the problem would be fixed?? That would be very useful.

**Comment by jschueller** [comment]
Unfortunately I do not have osx available to do that, only linux.

**Comment by jakirkham** [comment]
Looks like this will be fixed by PR ( https://github.com/conda-forge/qt-feedstock/pull/37 ).
