### ISSUE TITLE
QSessionManager linux-64/qt-4.8.7-1

### ISSUE THREAD

**Issue by looooo** [conda-forge/qt-feedstock#4]
building some conda packages with qt dependencies gives me this error:
```
invalid use of incomplete type ‘class QSessionManager’ manager.cancel();
```
 was there a change in the qt library? or is this related to the latest conda-forge qt build?

**Comment by ccordoba12** [comment]
We use almost the same recipes for conda-forge as for the default channels, so I don't know what's happening in your case.
