### ISSUE TITLE
Limit runtime requirements (on osx)

### ISSUE THREAD

**Issue by astaric** [conda-forge/qt-feedstock#41]
When installing qt from conda-forge channel, the following packages are installed:
```
"conda-forge::ca-certificates-2017.1.23-0 1",
"conda-forge::expat-2.1.0-2 1",
"conda-forge::icu-58.1-1 1",
"conda-forge::jpeg-9b-0 1",
"conda-forge::zlib-1.2.11-0 1",
"conda-forge::dbus-1.10.10-3 1",
"conda-forge::libpng-1.6.28-0 1",
"conda-forge::openssl-1.0.2k-0 1",
"conda-forge::freetype-2.7-1 1",
"conda-forge::qt-5.6.2-1 1"
```

while qt from defaults channel only installs
```
"icu-54.1-0 1",
"zlib-1.2.8-3 1",
"qt-5.6.2-0 1"
```

The one I am most concerned about is dbus, as it kindly asks to add a Launch daemon which I do not want to do. Are all of them really needed or were they inherited from the linux build?

**Comment by gillins** [comment]
I tried to add the software listed in the "Third Party Libraries" section of [this document](http://doc.qt.io/qt-5/configure-options.html) so there wouldn't be any conflicts between different versions (conda-forge vs Qt). I haven't checked these are being picked up properly however. And I see `pcre` has been missed.

I suspect `dbus` ended up in there to be the same as Linux but I can't remember. Would it break anything if it was removed?

**Comment by mingwandroid** [comment]
"Third Party Libraries" doesn't make the distinction between system libraries and bundled libraries. That's done in build.sh when you pass, e.g. `-qt-libjpeg` vs `-system-libjpeg` to `configure`. You should only add dependencies for the `-system-*` ones.

Unneeded dependencies give the solver much less wriggle room. You should attempt to ensure the dependencies are strictly required and that they are pinned only as tightly as is necessary.

Regarding conflicts:

1. macOS has a comprehensive (I'd actually say confusingly so) shared library loader (`dyld`) that supports relative paths, relative to all sorts of things. `conda-build` uses `@rpath` from that to ensure that the correct libraries are found.
2. AFAIK, most of the `-qt-foo` options end up creating a static library from that 3rd party library so do not even need shared library lookup.

**Comment by ccordoba12** [comment]
> Would it break anything if it was removed?

We need a recompilation. I'll create a PR to fix/remove unneeded  dependencies.

Adding dbus without considering the consequences doesn't make any sense to me. That's why we (at Continuum) didn't do it nor are we planning to do it.
