### ISSUE TITLE
Qt5 support ?

### ISSUE THREAD

**Issue by hadim** [conda-forge/qt-feedstock#5]
Any chance to get Qt5/PyQt5 here ?

**Comment by ccordoba12** [comment]
Yep, it will come in three weeks or a months. I'm traveling right now :-)

**Comment by hadim** [comment]
Awesome. Let me know if you need any help.

**Comment by jakirkham** [comment]
As this came up in our meeting earlier, copying core on this.

cc @conda-forge/core

**Comment by jakirkham** [comment]
Should note this is not something that is likely to build on CIs. So it likely will need to be built manually and uploaded. The process for such a thing still needs to be ironed out though.

**Comment by looooo** [comment]
The default qt5 from anaconda doesn't work for me, because it use icu 54.* and this isn't compatible with the newer boost versions. So if there are no other dependency issues, please use icu56. thanks, and nice regards.

**Comment by hadim** [comment]
@jakirkham why can't you build Qt5 automatically since you did it for Qt4 ? Is it a time constraint on CI website ?

If so do you know when someone will be able to build it manually and add it on conda forge ? I can help for building if necessary.

**Comment by jakirkham** [comment]
There was a similar issue with JPEG and Qt between defaults and conda-forge IIRC, @looooo. Keeping ours and defaults stack inline is longer term unmaintainable. Suggestions of downgrading our stack to match defaults has been quite controversial. Not sure what constraints defaults is operating under, but I do agree that upgrading on that end would help temporarily if feasible.

**Comment by jakirkham** [comment]
> @jakirkham why can't you build Qt5 automatically since you did it for Qt4 ? Is it a time constraint on CI website ?

Literally the constraints. 😆 Longer, more resources, etc.

> If so do you know when someone will be able to build it manually and add it on conda forge ? I can help for building if necessary.

So I think what you could help with if you are feeling so inclined is to write up the process for doing a manual upload as a [CFEP]( https://github.com/conda-forge/conda-forge-enhancement-proposals ). I think there is a lot of support for having manual built uploads in cases like this and it would be impractical to avoid it forever. However, I think our community would benefit if we outline the process of why it is done, who does it, how one carries it out, and what one needs to do to get a manually built package. If you would be willing to do that, I think that would go a long ways towards making it possible to solve this Qt issue and others in the near future.

**Comment by jakirkham** [comment]
> @jakirkham why can't you build Qt5 automatically since you did it for Qt4 ? Is it a time constraint on CI website ?

Literally the constraints. 😆 Longer, more resources, etc.

> If so do you know when someone will be able to build it manually and add it on conda forge ? I can help for building if necessary.

So I think what you could help with if you are feeling, @hadim, so inclined is to write up the process for doing a manual upload as a [CFEP]( https://github.com/conda-forge/conda-forge-enhancement-proposals ). I think there is a lot of support for having manual built uploads in cases like this and it would be impractical to avoid it forever. However, I think our community would benefit if we outline the process of why it is done, who does it, how one carries it out, and what one needs to do to get a manually built package. If you would be willing to do that, I think that would go a long ways towards making it possible to solve this Qt issue and others in the near future.

**Comment by ccordoba12** [comment]
> why can't you build Qt5 automatically since you did it for Qt4

This kind of comments is discouraging when people don't know what they are talking about. It took us (i.e. Continuum) almost a year, three persons and I'd say 300 hours of hard work to compile Qt5 in all platforms (we started with Qt 5.5 in October last year :-) It is (by far) the most complex and difficult package we have had to compile to date.

We are the only ones that provide Qt5 packages for Python 2.7 on Windows, and whose packages really work on Linux in CI services (try to install the PyQt5 wheels on Travis to see what I'm talking about! :-)

----

Now, after saying that, it's possible that Qt5 can be built on CircleCI. We just have to upload the (Continuum) recipe and try it :-)

**Comment by jakirkham** [comment]
Sure on CircleCI it may be possible. Though IIRC there were some issues building it on CircleCI at staged-recipes. In any event, it was my understanding this remains out of scope for Travis CI and AppVeyor. Is that not correct? If so, we would still benefit from a CFEP on manually built uploads.

**Comment by hadim** [comment]
@ccordoba12 sorry for that but I was only looking for information here. It's not obvious that Qt5 is much much harder than Qt5 to build. Now you said it I understand better the situation.

@jakirkham I could write a very preliminar draft proposal but I am don't have neither the writing skills in english neither the knowledge of conda-forge/conda-build to write a final version. I'll submit a PR when I'll have sometime.

**Comment by hadim** [comment]
A first draft is available here : https://github.com/conda-forge/conda-forge-enhancement-proposals/pull/5

**Comment by jakirkham** [comment]
Thanks for doing that @hadim. 

No worries on English writing skills. After all we are all Engineers not Copy Editors. 😄

Also I wouldn't worry about being an expert on conda-forge/conda-build. I think the fundamental issues are much more basic and relatable than that.

For instance, how can we ensure that things that are manually uploaded are built in the right manner and are safe for distribution? Who do we allow to upload these packages? When do we determine something must be built manually? What does one need to do to manually build a package? Etc. These are more questions of how we as a community want to approach this and less about technical jargon.

**Comment by hadim** [comment]
Ok. Let's continue the discussion in the proposal.

**Comment by ccordoba12** [comment]
> @ccordoba12 sorry for that but I was only looking for informations here.

Understood, but (for the next time :-) please try to be more careful on how you address your questions or comments. Your question

> why can't you build Qt5 automatically since you did it for Qt4

sounded to me like

> Why don't change a 4 for a 5 and make the magic happen?

and after all the troubles and headaches me and @mingwandroid had to pass through with Qt5, that really irritated me :-p

**Comment by jakirkham** [comment]
I see Qt5 is building `chromium`, which also rebuilds a lot of 3rd party stuff (much of which we also package). Am wondering if we can significantly cutdown on build time by having these things packaged separately and reused in Qt5. Sorry if I'm asking a question that has already been answered.

**Comment by ccordoba12** [comment]
I don't think so, unless you mess with Qt5 build system. Besides, Chromium is only built on macOS. The other OSes build WebKit.

**Comment by jakirkham** [comment]
Qt5 has been built and manually uploaded for all platforms since. Hence this is resolved.
