### ISSUE TITLE
installed Qt has no DB drivers

### ISSUE THREAD

**Issue by jschueller** [conda-forge/qt-feedstock#50]
seems on windows qt is built without database plugins (on linux it seems ok)
I see we have sqlite packages, maybe it could be added as dependency ?

**Comment by gillins** [comment]
More information here: http://doc.qt.io/qt-5/sql-driver.html

Not sure how it is working on Linux as documentation states default is no drivers. Feel free to submit a PR with how you think it should look (which drivers, plugins or builtins) and I can have a go at doing a new build...

**Comment by gillins** [comment]
Fixed by #51
