### ISSUE TITLE
no webkit support on osx ?

### ISSUE THREAD

**Issue by jschueller** [conda-forge/qt-feedstock#52]
hi,
I was wondering why qwtwebkit is not provided on osx (for my pyside recipe).
Looking at the build.sh it looks fairly complex so I wouldn't be surprised of a "no cant do" answer.

**Comment by mingwandroid** [comment]
Well, QtWebkit is deprecated (or it was, it might be coming back, I am not sure anymore), so we took the opportunity to provide QtWebengine instead as that was 'the future'.

We would have dumped QtWebkit on all systems had it been possible to compile QtWebengine with MSVC 2008 in all likelyhood.

Qt 5.9 doesn't come with QtWebkit at all, and, to build it for Qt 5.6.2 it requires downloading a separate, less supported source archive.

From what I am told, they are very similar and you can use `qtpy` to abstract many of the differences from `pyqt` based applications, though I don't know anything about `pyside`.

**Comment by jschueller** [comment]
ok, thanks
