### ISSUE TITLE
Extra dependencies on Linux

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/qt-feedstock#57]
Seems that `qt` 5.6 now has a run time dependency `chrpath` on Linux. At least it is being pulled in by the package. However I'm not seeing any corresponding update in the recipe about adding `chrpath`. It seems a little strange to add `chrpath` as this is only used during a build to update the RPATH in libraries. Not really understanding the value of having it at run time unless it is being used by qmake. Any thoughts on this?

**Comment by jakirkham** [comment]
Related it seems ruby is getting pulled in too. I'm pretty sure that is only needed for the build and not needed at runtime unless I'm missing something.

**Comment by ccordoba12** [comment]
> qt 5.6 now has a run time dependency chrpath on Linux.

Why is that? I mean, who did that change?

> I'm pretty sure that is only needed for the build

Correct. It's needed to build QtWebkit.

**Comment by jakirkham** [comment]
No clue. I can't find the corresponding recipe change ( https://github.com/conda-forge/qt-feedstock/issues/58 ). Presumably whoever built for Linux last.

**Comment by jakirkham** [comment]
As we now build on CI and have done a few builds since, this issue appears to have been resolved.
