### ISSUE TITLE
Recipe out-of-date on Linux

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/qt-feedstock#58]
Recently ran update on Linux and am seeing a lot of new dependencies getting pulled in that weren't being pulled in before like X11 packages, ruby, chrpath, and libuuid. For the most part, this seems like a positive change as it is cutting down our dependence on `yum_requirements.txt` ( https://github.com/conda-forge/qt-feedstock/issues/56 ), which is good. Some don't seem like they should be runtime dependencies, which is a separate discussion ( https://github.com/conda-forge/qt-feedstock/issues/57 ). However am concerned that there is not a corresponding update in the recipe. Am I just missing the commit somewhere?

**Comment by stuarteberg** [comment]
On a related note, our Linux packages for qt5 have been moved to the "broken" label on anaconda.org, which means they can't be downloaded anymore via the usual command (`conda install -c conda-forge qt=5`).

I haven't been keeping up with the discussions regarding the Linux package.  Is there a thread I can catch up on to better understand the situation?  Anything I can do to help?

**Comment by jakirkham** [comment]
Hmm...seems the recent Linux build was deleted. 😕

In any event, appears there is not a Linux build for build number 4 (the most recent one). Maybe if someone can do that build, we can upload that one. Happy to provide instructions if someone has time and is interested.

**Comment by stuarteberg** [comment]
>Happy to provide instructions if someone has time and is interested.

Are there any special instructions required beyond simply building the recipe within the `condaforge/linux-anvil` docker container?

**Comment by jakirkham** [comment]
It's actually much easier than that for Linux. Would drop/change the `skip` statement to allow a build on Linux and then [re-render]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) with the latest `conda-smithy`. This should create a script `ci_support/run_docker_build.sh`. Then just run that script. The package will be dropped in `build_artefacts/linux-64` when done.

**Comment by stuarteberg** [comment]
Interestingly, I can run `conda smithy rerender` from within the docker container, but I can't run it on my Mac:

```pytb
$ conda smithy rerender
Traceback (most recent call last):
  File "/miniforge/bin/conda-smithy", line 6, in <module>
    exit(main())
  File "/miniforge/lib/python3.6/site-packages/conda_smithy/cli.py", line 290, in main
    args.subcommand_func(args)
  File "/miniforge/lib/python3.6/site-packages/conda_smithy/cli.py", line 194, in __call__
    configure_feedstock.main(args.feedstock_directory)
  File "/miniforge/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 722, in main
    render_circle(env, config, forge_dir)
  File "/miniforge/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 72, in render_circle
    with fudge_subdir('linux-64', build_config=meta_config(meta)):
  File "/miniforge/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/miniforge/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 221, in fudge_subdir
    build_config.subdir = subdir
AttributeError: can't set attribute
```

**Comment by stuarteberg** [comment]
Anyway, the build is running now... I'll post again when (if) it completes.

**Comment by jakirkham** [comment]
Cool. Glad you got it to work.

Yeah you may need to update to `conda` 4.3, `conda-build` 2.1.x latest, and `conda-build-all` 1.1.1 as well. There have been a few hiccups along the road as these tools had used things that were not part of the public API (as there wasn't one), but are trying to do so now that things are getting standardized a bit.

**Comment by stuarteberg** [comment]
>Yeah you may need to update to conda 4.3, conda-build 2.1.x latest

Oops, right, I forgot that conda-smithy requires conda-build 2.  That was the issue.

**Comment by jakirkham** [comment]
Ah ok. Are you on `conda-build` 3 already? We haven't gotten there yet, but it looks pretty cool.

**Comment by ocefpaf** [comment]
@stuarteberg can you hold the fire on this one? 
I am looking, with @msarahan @mingandroid, into getting the defaults pkg compatible with conda-forge to avoid the manual uploads.

At least until we can build qt with our CI resources.

**Comment by jakirkham** [comment]
This appears to have been resolved. Closing. Feel free to open a new issue if we missed something.
