### ISSUE TITLE
/usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found

### ISSUE THREAD

**Issue by jschueller** [conda-forge/qt-feedstock#62]
Since the version 5.6.2-7 (fine with 5.6.2-6) I've got this error in the pyside2 feedstock:

```
Traceback (most recent call last):
  File "/feedstock_root/build_artefacts/pyside2_1513781587706/test_tmp/run_test.py", line 11, in <module>
    import PySide2.QtHelp
ImportError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /feedstock_root/build_artefacts/pyside2_1513781587706/_t_env/lib/python2.7/site-packages/PySide2/../../../libQt5CLucene.so.5)
TESTS FAILED: pyside2-2.0.0.dev0-py27_2.tar.bz2
```

**Comment by mingwandroid** [comment]
Adopting our compilers would prevent this kind of problem from happening again.

**Comment by jschueller** [comment]
what compilers ? I dont see what to change.

**Comment by isuruf** [comment]
Looks like this was compiled with the conda `gcc` package instead of the `gcc` package in the container.
As a workaround until this is fixed, you can add `libgcc` as a requirement.
