### ISSUE TITLE
Build without ICU

### ISSUE THREAD

**Issue by Code-ReaQtor** [conda-forge/qt-feedstock#63]
Hello,

I opened an issue in pyside-feedstock and I was directed here.

https://github.com/conda-forge/pyside2-feedstock/issues/9

**Comment by ccordoba12** [comment]
I think ICU is a hard Qt dependency, therefore it cannot be removed.

**Comment by Code-ReaQtor** [comment]
ICU is a optional https://wiki.qt.io/Building_Qt_5_from_Git

**Comment by nicoddemus** [comment]
@Code-ReaQtor what would be the consequences of building without ICU?

**Comment by nicoddemus** [comment]
Looking at the page there is this blurb about Windows:

> ICU on Windows
Qt 5 can make use of the ICU library for UNICODE and Localization support. This is required for building Qt WebKit. You can use pre-compiled versions of ICU with a Visual Studio 2010 dependency from the website, get pre-compiled versions for different compilers from download.qt.io, or compile ICU on your own.

Also the page suggests that it is a requirement for building WebKit on Linux:

> WebKit doesn't compile, missing ICU
Currently there is no configure time check for ICU, so install it through the package manager through

It would also be interesting to know why you want to compile Qt without ICU, @Code-ReaQtor.

**Comment by Code-ReaQtor** [comment]
@nicoddemus Qt Widgets-based applications that does not use Webkit still requires ICU which increases installer/package size. Even simple User Interfaces (simple window/dialog) are somewhat "bloated" due to ICU dependency.

In my case, I built Inno Setup (**_with compression_**)-based apps that reaches 20MB with ICU but should only be less that 8MB (**_without ICU_**).

**Comment by mingwandroid** [comment]
ICU is the recommended approach to codepage conversion and fast becoming the defacto standard way (R also adopted it recently). Using something else is a bad choice. I'm of the opinion this should be closed.

**Comment by mingwandroid** [comment]
You are free to make your own changes and host your own qt package built according to your preferences, but IMHO conda-forge and the Anaconda Distribution should stick to the vanilla, most compatible (for app behaviour across OSes) recommended and most functional approaches, esp for foundational framework libraries.

**Comment by ccordoba12** [comment]
> I'm of the opinion this should be closed.

Agreed. @Code-ReaQtor, you're welcome to take the recipe hosted here and modified as you need. Then you could build your packages as you wish.
