### ISSUE TITLE
Relic qt.conf after uninstallation

### ISSUE THREAD

**Issue by giumas** [conda-forge/qt-feedstock#71]
The command `conda uninstall qt` does not currently remove the installed `qt.conf` file. 

This triggers issues with other Qt-based installations that will be installed in the same environment (e.s., the official `Pyside2` wheel): 

- https://github.com/conda-forge/qt-feedstock/issues/70
- https://bugreports.qt.io/browse/PYSIDE-761

**Comment by mingwandroid** [comment]
Removing this file doesn't fix your bug it just pushes it around a bit.

> This triggers issues with other Qt-based installations

This is completely unsupported and unsupportable!

Keeping the bug open because we probably should clean up here.

**Comment by mingwandroid** [comment]
The moment you used PIP to install the `PySide2` wheel you are no longer using any of our Qt libraries so you are no dealing with `Anaconda Distribution` software exclusivevly, or rather, you are dealing with a Frankenstien's monster of a mixed up distro.

If you want to progress `PySide2` within the `Anaconda Distribution` then please investigate making a package and submitting it to conda-forge.

**Comment by giumas** [comment]
There is already a [`PySide2` conda-forge package](https://github.com/conda-forge/pyside2-feedstock), and it relies on this package. As such, until this package does not get updated to 5.11 (or, more likely, LTR 5.12), the `PySide2` package cannot be compiled with the latest improvements in PySide2 (since [5.11+ is the only supported](http://blog.qt.io/blog/2018/06/13/qt-python-5-11-released/?hsCtaTracking=6a98599e-2336-40fc-bb33-940e46e48720%7C96301a53-b975-4aba-80c4-ded982b9ae29)). 

Based on your comment [here](http://blog.qt.io/blog/2018/06/13/qt-python-5-11-released/#comment-1203934), I don't think that the update to 5.11/12 will come anytime soon. This is why I have attempted to use the official PyPi wheel.

**Comment by mingwandroid** [comment]
Well you shouldn't user that when within anaconda.

If you are a software developer your night consider helping out with conda-forge?

**Comment by giumas** [comment]
> If you are a software developer your might consider helping out with conda-forge?

I am more a researcher than a software developer, but surely open to help and contribute to the conda-forge cause.

**Comment by ocefpaf** [comment]
This is issue is stale and the solution seems to be a `qt` update, making this a dup from #101. Closing it.
