### ISSUE TITLE
linux64 qt compiled with cups support?

### ISSUE THREAD

**Issue by BrendanMD** [conda-forge/qt-feedstock#76]
Is the linux64 qt library compiled with cups support? It can only print to file i.e. printers are not detected.
To replicate run the Qt5 code on https://stackoverflow.com/questions/8193920/how-to-use-qprinter-and-qprintpreviewdialog/8196526 .  The only printer listed is print to file.  I can print from other linux apps, such as Firefox.

Environment & Details:
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.3
DISTRIB_CODENAME=rosa
DISTRIB_DESCRIPTION="Linux Mint 17.3 Rosa"
NAME="Ubuntu"
VERSION="14.04.1 LTS, Trusty Tahr"

pyqt                      5.9.2            py36h22d08a2_1
qt                        5.9.6                h8703b6f_2
qtawesome                 0.4.4            py36h609ed8c_0
qtconsole                 4.3.1            py36h8f73b5b_0
qtpy                      1.4.0                    py36_0

active environment : None
user config file : /home/brendan/.condarc
 populated config files : /home/brendan/.condarc
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.6.4.final.0
       base environment : /home/brendan/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/brendan/anaconda3/pkgs
                          /home/brendan/.conda/pkgs
       envs directories : /home/brendan/anaconda3/envs
                          /home/brendan/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.4 Linux/3.19.0-32-generic ubuntu/14.04 glibc/2.19
                UID:GID : 5386:2051
             netrc file : /home/brendan/.netrc
           offline mode : False

Edit: deleted code sample. Too much markup mangling.

**Comment by mingwandroid** [comment]
Probably not. PR welcome.

**Comment by BrendanMD** [comment]
Originally I submitted a bug to Spyder because my original issue was printing source code. I closed the issue there and opened one here when I realized the problem was likely how qt was compiled. If I ever learn about packaging for conda I will contribute, but now is not that time.

**Comment by mingwandroid** [comment]
`conda-forge` are our upstream for everything, but for Qt only defaults provides `5.9.6` at present (because Qt builds are tricky and takes many hours to build and thus to improve). I don't know how compatible default's Qt is with conda-forge packages, maybe not hugely.

For now, all I can suggest is printing to a `.pdf` then using a system pdf viewer to print it.

**Comment by ccordoba12** [comment]
> For now, all I can suggest is printing to a .pdf then using a system pdf viewer to print it.

My suggestion exactly.

**Comment by ocefpaf** [comment]
@BrendanMD `qt` was updated and maybe this was fixed. Please re-open if not.
