### ISSUE TITLE
gcc7: missing qtopengl

### ISSUE THREAD

**Issue by looooo** [conda-forge/qt-feedstock#80]
In the newly available gcc7-qt5.6 build qtopengl is missing. I guess it should be included, because it is also included for the gcc4.8 based builds. Maybe libgl isn't found/configured correctly. I see this in many builds and adding `- {{ cdt('mesa-libgl-devel') }}  # [linux]` maybe helps. But I am not sure as this is good practice as this also pulls in `libx11-cos6-x86_64`.

**Comment by mingwandroid** [comment]
> as this also pulls in libx11-cos6-x86_64

I think you may misunderstand how CDT packages work. They are *never* pulled in or installed on end users' systems. They act only as build time proxies for system libraries.

**Comment by looooo** [comment]
Either it is a problem or not if xorg-x11 and libx11-cos6-x86_64 are installed in build-env and host-env.

**Comment by mingwandroid** [comment]
It is never installed in host envs. Was I unclear in that?

Until cf provides libGL you have no option. But honestly it's far and arrest the best option so I really really don't get your injections in the slightest. What exactly is wrong with requiring a CDT packages at build time?  What problem will that create for the built package. Yeah you need to use your system GL libs, but those will be far faster than a Mesa software renderer for most people as it'll use those GPUs.

**Comment by mingwandroid** [comment]
> Either it is a problem or not if xorg-x11 and libx11-cos6-x86_64 are installed in build-env and host-env.

Please assess the value of this comment from a 3rd party person perspective.

**Comment by looooo** [comment]
refs:
https://github.com/conda-forge/pyqt-feedstock/pull/41
https://github.com/conda-forge/qt-feedstock/pull/81

**Comment by looooo** [comment]
thanks solved with: https://github.com/conda-forge/pyqt-feedstock/pull/41
