### ISSUE TITLE
Use `xorg-libxfixes`

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/qt-feedstock#85]
Appears we are using a CDT for [`libxfixes`]( https://github.com/conda-forge/qt-feedstock/blob/a16262b187248038b8d2f14a9cb0416d107448a6/recipe/meta.yaml#L39 ). However we have the conda-forge package [`xorg-libxfixes`]( https://github.com/conda-forge/xorg-libxfixes-feedstock ), which should work in place of it. Would be good to switch over if we can.

**Comment by ocefpaf** [comment]
We decided to go with the CDTs for now. There is a CFEP, https://github.com/conda-forge/conda-forge-enhancement-proposals/pull/7, that we should vote/discuss more and than we can make changes like this everywhere. (Preferível with a migrator.)

Closing this as stale.
