### ISSUE TITLE
Split WebKit from Qt

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/qt-feedstock#99]
This might reduce build times and make this a bit smaller.

**Comment by CJ-Wright** [comment]
This might also be a good first step towards newer qt

**Comment by gillins** [comment]
FYI we already have a feedstock for this: https://github.com/conda-forge/qtwebkit-feedstock/ (created when webkit wasn't available on the OSX build of `qt`).

**Comment by CJ-Wright** [comment]
great!

**Comment by ocefpaf** [comment]
We just archived that feedstock and went with a single `qt` package with `qtwebkit`.
The time saved won't help us build `qt` anyway, so closing this.
